Add `Entry.elements` property (#3226)
* add property Elements to Entry class

* use new Structure.elements and Composition.elements properties

previously (Structure|Entry).composition.elements

* add test_elements in TestPDEntry and TestTransformedPDEntry

* revert find-replace in Structure.elements

* add PourbaixEntry.elements property

* fix AttributeError on pymatgen/analysis/pourbaix_diagram.py:314

# normalization_factor, num_atoms should work from superclass
>       return self.__getattribute__(item)
E       AttributeError: 'MultiEntry' object has no attribute 'entry'

---------

Signed-off-by: Janosh Riebesell <janosh.riebesell@gmail.com>