Run CI with two different `uv` resolution strategies: `highest` and `lowest-direct` (#3852)
* fix typing_extensions ImportError

https://github.com/materialsproject/pymatgen/pull/3752#issuecomment-2142954988

* bump min ase to 3.23.0

* test both lowest-direct and highest uv package resolutions in CI

* establish some loose lower bounds on all deps

needed for deps install with --resolution=lowest-direct to work

* netcdf4>=1.6

* pin chgnet==0.3.6

* try chgnet==0.3.5

* bump pre-commit hooks

* imperative doc strings

* doc str white space

* test_string->test_str

* ruff auto fixes

* matgl>=1.1.1 numba>=0.55

* try fix netcdf4 install

* h5py>=3.9.0

* monty>=2024.5.24

fixes TypeError: deprecated() got an unexpected keyword argument 'deadline'

* revert TestWavecar to again inherit from PymatgenTest

* h5py>=3.11.0

* phonopy>=2.23

* scipy>=1.13.0

* matplotlib>=3.8

* requests>=2.32

* don't run oldest/newest supported python twice on linux AND windows

* fix bad refactor in get_atom_map

fixes KeyError: 'Co' ipot = self.pot_dict[el.symbol]