Unittest2pytest (#2810)
* only raise ValueError on missing legacy PMG_MAPI_KEY if env var CI=true

* dunder vars below imports

* unittest2pytest --write --nobackups pymatgen/analysis

followed by adding `from pytest import approx`
isort --add-import 'from pytest import approx' $(git status -s | cut -c4-)

* fix StructureGraphTest.test_weight_statistics()

E       assert 3.826872473271329e-11 == 0 ± 1.0e-12
E         comparison failed
E         Obtained: 3.826872473271329e-11
E         Expected: 0 ± 1.0e-12

pymatgen/analysis/tests/test_graphs.py:484: AssertionError

* unittest2pytest --write --nobackups pymatgen/electronic_structure

* unittest2pytest --write --nobackups pymatgen

* fix KabschMatcherSiTest.test_rotated_molecule

>       assert rmsd == approx(0.0, 6)
E       assert 2.4325092169869034e-07 == 0.0 ± 1.0e-12
E         comparison failed
E         Obtained: 2.4325092169869034e-07
E         Expected: 0.0 ± 1.0e-12

pymatgen/analysis/tests/test_molecule_matcher.py:592: AssertionError

* unittest2pytest --write --nobackups pymatgen

* fix StructureMatcherTest.test_fit

>       assert sm_coarse.fit(s1, s2) is True
E       assert True is True
E        +  where True = <bound method StructureMatcher.fit of
pymatgen/analysis/tests/test_structure_matcher.py

* auto-migration missed passing places of assertAlmostEqual(places=int) as pytest.approx(abs=1e-int)

places was just passed as 2nd argument to pytest.approx() which is rel

* more fixing of missing pytest.approx(abs=1e-places)

* fix test_dos_fp_exceptions AttributeError: 'ExceptionInfo' object has no attribute 'exception'

* fix flake8 B017

pymatgen/util/tests/test_coord.py:52:9: B017 assertRaises(Exception): or pytest.raises(Exception) should be considered evil. It can lead to your test passing even if the code being tested is never executed due to a typo. Either assert for a more specific exception (builtin or custom), use assertRaisesRegex, or use the context manager form of assertRaises.

pymatgen/util/tests/test_provenance.py:135:9

* fix TypeError in FuncTest.test_get_bond_length _________________________

self = <core.tests.test_bonds.FuncTest testMethod=test_get_bond_length>

    def test_get_bond_length(self):
>       assert pytest.approx(get_bond_length("C", "C", abs=1e-1) - 1.54) == 0
E       TypeError: get_bond_length() got an unexpected keyword argument 'abs'

pymatgen/core/tests/test_bonds.py:67

* fix TestLobsterNeighbors.test_cation_anion_mode_without_ions

    def test_cation_anion_mode_without_ions(self):
        with pytest.raises(ValueError) as err:
            _ = LobsterNeighbors(
                are_coops=False,
                filename_ICOHP=os.path.join(test_dir_env, "../ICOHPLIST.lobster"),
                structure=Structure.from_file(os.path.join(test_dir_env, "../POSCAR")),
                valences_from_charges=False,
                additional_condition=1,
            )
>       assert (
            str(err.exception) == "Valences cannot be assigned, additional_conditions 1 and 3 and 5 and 6 will not work"
        )
E       AttributeError: 'ExceptionInfo' object has no attribute 'exception'

* fix StructureNLCase.test_historynodes

>       return HistoryNode(h_node["name"], h_node["url"], h_node["description"])
E       KeyError: 'description'

pymatgen/util/provenance.py:101: KeyError

* fix GaussianOutputTest.test_geo_opt

>       assert gau.opt_structures[-1].cart_coords[:3].tolist() == approx(coords)
E       TypeError: pytest.approx() does not support nested data structures: [-13.642932, 0.71506, 0.000444] at index 0
E         full sequence: [[-13.642932, 0.71506, 0.000444],
E        [-13.642932, -0.71506, 0.000444],
E        [-12.444202, 1.416837, 0.000325]]

pymatgen\io\tests\test_gaussian.py:414: TypeError